services:
    entity_factory:
        class: Gemba\AdminBundle\Factory\EntityFactory
        arguments: [@service_container]

    type_factory:
        class: Gemba\AdminBundle\Factory\TypeFactory
        arguments: [@service_container]

    form_factory:
        class: Gemba\AdminBundle\Factory\FormFactory
        arguments: [@service_container]

    submit_listener:
        class: Gemba\AdminBundle\EventListener\FormSubmitListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener , event: form.post_bind , method: onSubmit }

    block_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gemba\AdminBundle\Entity\Block ]

    block:
        class: Gemba\AdminBundle\Decorator\Repository
        arguments: [@block_repository]

    layout_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gemba\AdminBundle\Entity\Layout ]

    layout:
        class: Gemba\AdminBundle\Decorator\Repository
        arguments: [@layout_repository]

    smalltext_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gemba\AdminBundle\Entity\Smalltext ]

    smalltext:
        class: Gemba\AdminBundle\Decorator\Repository
        arguments: [@smalltext_repository]

    blog_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gemba\AdminBundle\Entity\Blog ]

    blog:
        class: Gemba\AdminBundle\Decorator\Repository
        arguments: [@blog_repository]

    comment_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gemba\AdminBundle\Entity\Comment ]

    comment:
        class: Gemba\AdminBundle\Decorator\Repository
        arguments: [@comment_repository]

    slider_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gemba\AdminBundle\Entity\Slider ]

    slider:
        class: Gemba\AdminBundle\Decorator\Repository
        arguments: [@slider_repository]

    bottom_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gemba\AdminBundle\Entity\Bottom ]

    bottom:
        class: Gemba\AdminBundle\Decorator\Repository
        arguments: [@bottom_repository]

    copyright_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gemba\AdminBundle\Entity\Copyright ]

    copyright:
        class: Gemba\AdminBundle\Decorator\Repository
        arguments: [@copyright_repository]

    logo_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gemba\AdminBundle\Entity\Logo ]

    logo:
        class: Gemba\AdminBundle\Decorator\Repository
        arguments: [@logo_repository]

    seo_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gemba\AdminBundle\Entity\Seo ]

    seo:
        class: Gemba\AdminBundle\Decorator\Repository
        arguments: [@seo_repository]

    news_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gemba\AdminBundle\Entity\News ]

    news:
        class: Gemba\AdminBundle\Decorator\Repository
        arguments: [@news_repository]

    top_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gemba\AdminBundle\Entity\Top ]

    top:
        class: Gemba\AdminBundle\Decorator\Repository
        arguments: [@top_repository]

    menu_chuck:
        class: Gemba\AdminBundle\Chuck\MenuChuck
        arguments: [@service_container]

    top_chuck:
        class: Gemba\AdminBundle\Chuck\TopChuck
        arguments: [@service_container]

    bottom_chuck:
        class: Gemba\AdminBundle\Chuck\BottomChuck
        arguments: [@service_container]

    copyright_chuck:
        class: Gemba\AdminBundle\Chuck\CopyrightChuck
        arguments: [@service_container]

    logo_chuck:
        class: Gemba\AdminBundle\Chuck\LogoChuck
        arguments: [@service_container]